// kotlinx-datetime classes are immutable — treat as stable
kotlinx.datetime.LocalDate
kotlinx.datetime.LocalDateTime
kotlinx.datetime.LocalTime
kotlinx.datetime.Instant
kotlinx.datetime.TimeZone
kotlinx.datetime.FixedOffsetTimeZone
kotlinx.datetime.UtcOffset
kotlinx.datetime.YearMonth
